### ISSUE TITLE
Update to the current version of open62541

### ISSUE THREAD

**Issue by fradaxx** [Pro/open62541-esp32#10]
Dear @Pro,

sorry to disturb you about a question that can be annoying but I would like to ask you for some help about the possibility to update this valuable demo to the current version of open62541.

For didactic purposes a couple of years ago I successfully adapted and compiled your demo on a couple of ESP32-based development boards; however I would like to have the opportunity to update the demo with the latest releases of open62541.

Due to the unavailability of the single-source files (open62541.h and open62541.c) on the official open62541 project repository, I would like to ask you if you can consider the possibility to publish (in this or in the open62541 project repository) some detailed info on how to generate those amalgamated source files using CMake.

My limited experience with CMake doesn't permit to me to do this fundamental step by myself.

Thank you in advance for your support.

Regards

Francesco

**Comment by Pro** [comment]
Hi Francesco, unfortunately I do not have the needed time to maintain this repository, nor provide any community support.

You can try to reach out to the open62541 community for getting the amalgamated files. Ideally create an issue in the open62541 repo

**Comment by fradaxx** [comment]
> Hi Francesco, unfortunately I do not have the needed time to maintain this repository, nor provide any community support.
> 
> You can try to reach out to the open62541 community for getting the amalgamated files. Ideally create an issue in the open62541 repo

OK, thank you anyway. I'll follow your hints!

Regards.
